/*

 GAME-SCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 28 x 18
   Tile set      : C:\Users\Tanjh\Desktop\BkgSpriteSheet.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __game_screen_h_INCLUDE
#define __game_screen_h_INCLUDE

#define game_screenWidth 28
#define game_screenHeight 18
#define game_screenBank 0

extern const unsigned char game_screen[];

#endif

/* End of GAME-SCREEN.H */
