/*

 HUD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : C:\Users\Tanjh\Desktop\BkgSpriteSheet.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __hud_h_INCLUDE
#define __hud_h_INCLUDE

#define hudWidth 20
#define hudHeight 1
#define hudBank 0

extern const unsigned char hud[];

#endif

/* End of HUD.H */
