/*

 HUD.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : C:\Users\Tanjh\Desktop\BkgSpriteSheet.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hudWidth 20
#define hudHeight 1
#define hudBank 0

const unsigned char hud[] =
{
  0x60,0x00,0x22,0x04,0x00,0x61,0x02,0x01,0x01,0x26,
  0x00,0x1A,0x1E,0x1D,0x27,0x01,0x01,0x01,0x01,0x01
};

/* End of HUD.C */
