/*

 SPRITE_SHEET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 19

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __sprite_sheet_h_INCLUDE
#define __sprite_sheet_h_INCLUDE

/* Bank of tiles. */
#define spriteBank 0
/* Start of tile array. */
extern const unsigned char sprite[];

#endif

/* End of SPRITE_SHEET.H */
