/*

 STATS-SCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Tanjh\Desktop\BkgSpriteSheet.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __stats_screen_h_INCLUDE
#define __stats_screen_h_INCLUDE

#define stats_screenWidth 20
#define stats_screenHeight 18
#define stats_screenBank 0

extern const unsigned char stats_screen[];

#endif

/* End of STATS-SCREEN.H */
